### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by kiriland** [AxDSan/dnSpy-StringsAnalyzer#1]
So when i'm running the dnSpy _(ver.3.0.2)_ , it gives me an error .

>  **dnlib wasn't compiled with THREAD_SAFE defined.** 

Hopefully u will resolve this miserable problem.

**Comment by AxDSan** [comment]
Hello, Thanks for reporting, I'm also aware of a couple of issues with this particular version of dnSpy that the plugin itself won't work or compile.

Will work on it when I get some time, will also try to update the whole project as it seemed to have compatibility issues.

**Comment by AxDSan** [comment]
Fixed everything as with the new version concerns, at least with 3.0.1.0 works fine just like before.

Still fixing stuff and getting modules to work directly from the 'Get String' button instead of loading a "hardcoded" one.

For now I'm closing this, if any other issue arises don't hesitate to open a new ticket.
Stay tuned.
